namespace SP2Builder.ManifoldRuntime
{
	public enum ManifoldError
	{
		NO_ERROR,
		NON_FINITE_VERTEX,
		NOT_MANIFOLD,
		VERTEX_INDEX_OUT_OF_BOUNDS,
		PROPERTIES_WRONG_LENGTH,
		MISSING_POSITION_PROPERTIES,
		MERGE_VECTORS_DIFFERENT_LENGTHS,
		MERGE_INDEX_OUT_OF_BOUNDS,
		TRANSFORM_WRONG_LENGTH,
		RUN_INDEX_WRONG_LENGTH,
		FACE_ID_WRONG_LENGTH,
		INVALID_CONSTRUCTION,
		RESULT_TOO_LARGE
	}

	internal enum ManifoldOpType
	{
		ADD,
		SUBTRACT,
		INTERSECT
	}
}